const FIELD_LENGTH_RATIO = 1.6;
const DATA_AMOUNT = 10;
const ACTION_RANDOM_PERCENT = 50;
const HOOK_TIMEOUT = 50_000;
const CONNECTION_CHECK_INTERVAL = 200;

export {
    FIELD_LENGTH_RATIO,
    DATA_AMOUNT,
    ACTION_RANDOM_PERCENT,
    HOOK_TIMEOUT,
    CONNECTION_CHECK_INTERVAL,
};
