version: '3.4'
networks:
  games-network:
    external: true

services:
  database:
    extends:
      file: docker-compose.base.yml
      service: database
    image: m20a20x/games:database
    container_name: database-test

  cdn:
    extends:
      file: docker-compose.base.yml
      service: cdn
    build:
      dockerfile: docker/configs/cdn/Dockerfile.test
    environment:
      NODE_ENV: test
      JWT_SECRET: ${JWT_SECRET}
      SPECS_DATA_AMOUNT: ${SPECS_DATA_AMOUNT}
      SPECS_HOOK_TIMEOUT_MS: ${SPECS_HOOK_TIMEOUT_MS}
    image: m20a20x/games:cdn
    container_name: cdn-test
    command: yarn test:quick cdn

  server:
    extends:
      file: docker-compose.base.yml
      service: server
    build:
      dockerfile: docker/configs/server/Dockerfile.test
    environment:
      NODE_ENV: test
    image: m20a20x/games:server
    container_name: server-test
    command: yarn test:quick server

  client:
    extends:
      file: docker-compose.base.yml
      service: client
    build:
      dockerfile: docker/configs/client/Dockerfile.test
    environment:
      NODE_ENV: test
      SPECS_DATA_AMOUNT: ${SPECS_DATA_AMOUNT}
      SPECS_HOOK_TIMEOUT_MS: ${SPECS_HOOK_TIMEOUT_MS}
    image: m20a20x/games:client
    container_name: client-test
    command: yarn test:quick client

