const DATABASE_NAME = 'games';
const DATABASE_IP = '127.0.0.1';
const DATABASE_PORT = 3306;
const PORT = 5000;
const WS_PORT = 8081;

export { DATABASE_IP, DATABASE_NAME, DATABASE_PORT, PORT, WS_PORT };
