const DATABASE_NAME = 'games';
const DATABASE_IP = '127.0.0.1';
const DATABASE_PORT = 3306;
const PORT = 5000;
const WS_PORT = 8081;
const DATABASE_HEALTHCHECK_TIMEOUT = 300;
const DISK_THRESHOLD_PERCENT = 0.85;
const MEM_HEAP_THRESHOLD = 1024 ** 3;
const MEM_RSS_THRESHOLD = 1024 ** 3;

export {
    DATABASE_IP,
    DATABASE_NAME,
    DATABASE_PORT,
    PORT,
    WS_PORT,
    DATABASE_HEALTHCHECK_TIMEOUT,
    DISK_THRESHOLD_PERCENT,
    MEM_HEAP_THRESHOLD,
    MEM_RSS_THRESHOLD,
};
