FROM node:18 as base
WORKDIR /usr/src/app/

RUN --mount=type=cache,target=~/AppData/Local/Yarn/Cache/v4 \
    --mount=type=bind,source=lerna.json,target=lerna.json \
    --mount=type=bind,source=package.json,target=package.json \
    --mount=type=bind,source=packages/client/package.json,target=packages/client/package.json \
    --mount=type=bind,source=yarn.lock,target=yarn.lock \
    yarn install --frozen-lockfile --non-interactive --ignore-scripts

COPY --chown=app:app ./package.json ./lerna.json ./jest.config.json ./
COPY --chown=app:app ./packages/shared/src/ ./packages/shared/src/

WORKDIR /usr/src/app/packages/client/
COPY --chown=app:app ./packages/client/package.json ./packages/client/jest.config.cjs ./packages/client/tsconfig.json ./
COPY --chown=app:app ./packages/client/src/ ./src/
COPY --chown=app:app ./packages/client/specs/ ./specs/

FROM node:18-alpine
WORKDIR /usr/src/app/

COPY --from=base /usr/src/app/ .
CMD ["yarn", "test"]
