import { Algorithm } from 'jsonwebtoken';

const JWT_EXPIRE_TIME_S = 3600;
const JWT_ALGORITHM: Algorithm = 'HS256';
const REFRESH_TOKEN_EXPIRE_TIME_MS = 7_776_000_000;
const DATABASE_HEALTHCHECK_TIMEOUT_MS = 300;
const DISK_THRESHOLD_PERCENT = 0.85;
const MEM_HEAP_THRESHOLD = 1024 ** 3;
const MEM_RSS_THRESHOLD = 1024 ** 3;

const NODE_ENV_PROD = 'prod';

export {
    JWT_EXPIRE_TIME_S,
    JWT_ALGORITHM,
    REFRESH_TOKEN_EXPIRE_TIME_MS,
    DISK_THRESHOLD_PERCENT,
    DATABASE_HEALTHCHECK_TIMEOUT_MS,
    MEM_HEAP_THRESHOLD,
    MEM_RSS_THRESHOLD,
    NODE_ENV_PROD,
};
