const FIELD_LENGTH_RATIO = 1.6;
const DATA_AMOUNT = 20;
const HOOK_TIMEOUT = 50_000;
const CONNECTION_CHECK_INTERVAL = 200;

export {
    FIELD_LENGTH_RATIO,
    DATA_AMOUNT,
    HOOK_TIMEOUT,
    CONNECTION_CHECK_INTERVAL,
};
