FROM node:18 as base
WORKDIR /usr/src/app/

RUN --mount=type=cache,target=~/AppData/Local/Yarn/Cache/v4 \
    --mount=type=bind,source=lerna.json,target=lerna.json \
    --mount=type=bind,source=package.json,rw,target=package.json \
    --mount=type=bind,source=packages/server/package.json,target=packages/server/package.json \
    --mount=type=bind,source=yarn.lock,target=yarn.lock \
    yarn install --frozen-lockfile --non-interactive --ignore-scripts \
    && yarn upgrade bcrypt --frozen-lockfile --non-interactive

COPY --chown=app:app ./package.json ./lerna.json ./jest.config.json ./
COPY --chown=app:app ./packages/shared/src/ ./packages/shared/src/

WORKDIR /usr/src/app/packages/server/
COPY --chown=app:app ./packages/server/package.json ./packages/server/jest.config.js ./packages/server/tsconfig.json ./
COPY --chown=app:app ./packages/server/src/ ./src/
COPY --chown=app:app ./packages/server/specs/ ./specs/

FROM node:18-alpine
WORKDIR /usr/src/app/

COPY --from=base /usr/src/app/ .
CMD ["yarn", "test"]
